# NOTE: This Conda environment is primarily for automated testing, at NCI use
# the 'analysis3' environment

name: aus400-cookbook
channels:
    - coecms
    - conda-forge
dependencies:
    - python >= 3.8
    - climtas
    - xarray
    - pandas
